name: expiry_date_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  flutter_local_notifications: ^17.1.2
  # awesome_notifications: ^0.9.3+1
  timezone: ^0.9.3
  firebase_messaging: ^14.9.3
  permission_handler: ^11.3.1
  fluttertoast: ^8.2.5
  flutter_timezone: ^1.0.8
  shared_preferences: ^2.2.3
  uuid: ^4.4.0
  percent_indicator: ^4.2.3
  get: ^4.6.6
  # flutter_launcher_icons: ^0.13.1
  # rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # flutter_launcher_icons: ^0.13.1

# flutter_launcher_icons:
# android: "launcher_icon"
# ios: true
# image_path: "assets/icons/expiry_watch_icon.png"
# git:
#     url: https://github.com/Davenchy/flutter_launcher_icons.git
#     ref: fixMinSdkParseFlutter2.8
# min_sdk_android: 21

flutter:
  uses-material-design: true
